name: Build and Push Container RC-MVSnet
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      GCP_SA_KEY:
        required: true
      GCP_PROJECT:
        required: true

jobs:
  build-rc-mvsnet:
    name: Build RC-MVSnet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            gcr.io/${{ secrets.GCP_PROJECT }}/rc-mvsnet:latest
            gcr.io/${{ secrets.GCP_PROJECT }}/rc-mvsnet:${{ inputs.tag }}
